Added an array_filter expression function
php-etl/array-expression-language pull request #6
Opened 2022-04-13 08:05 UTC by sebprt

2022-04-20 08:18 UTC, gplanchat requested changes

2022-04-20 08:18 UTC, gplanchat commented on src/ArrayExpressionLanguageProvider.php
> +            ExpressionFunction::fromPhp('array_filter'),
```suggestion
            ExpressionFunction::fromPhp('array_filter', 'filter'),
```

Il manque de la doc sur cette fonction et des callback utilisables

2022-04-20 12:36 UTC, gplanchat requested changes

2022-04-20 12:36 UTC, gplanchat commented on README.md
> +* `map(callable $callback, iterable $source) : iterable`
J'ai un gros doute que ça fonctionne, tu as testé ce que tu as écrit ?

2022-04-21 06:55 UTC, sebprt commented on README.md
> +* `map(callable $callback, iterable $source) : iterable`
Effectivement ça ne fonctionne pas.

J'ai ajouté un test et changé la doc.

2022-04-25 08:29 UTC, gplanchat requested changes

2022-04-25 08:29 UTC, gplanchat commented on src/ArrayExpressionLanguageProvider.php
> +            ExpressionFunction::fromPhp('array_filter', 'arrayFilter'),
J'ai l'impression qu'on a quand même une incohérence par rapport aux autres fonctions. `reduce`, `join` et `map` travaillent sur un type `iterable`, pas un type `array`.

On a besoin de cohérence dans toutes les fonctions.

2022-05-02 15:42 UTC, gplanchat approved these changes

2022-05-02 15:43 UTC, merged